version: '3.8'

services:
  app:
    build: .
    depends_on:
      - selenium
    environment:
      SELENIUM_URL: ${SELENIUM_URL:-http://selenium:4444/wd/hub}
      WEBHOOK_URL: ${WEBHOOK_URL:-https://discord.com/api/webhooks/xxx/xxx}

  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2g  # important for Chrome stability
